### ISSUE TITLE
Jukebox starts the disc twice

### ISSUE THREAD

**Issue by LordRazen** [EngineHub/CraftBook#1196] opened 2020-05-02 14:08 UTC
Version: 3.10.2-SNAPSHOT;4573-d8a3e9d + 1.15.2:

If you add a button directly on the Jukebox (with activated Jukebox mechanism ofc) the disc starts twice. You can hear this in the first second when the music starts, that the first noice is doubled. 

If you add the button on a solid block and place the jukebox next to this solid block, the disc is played one time only.

**Comment by me4502** [comment] 2020-05-02 14:12
This is due to a bug in Spigot, the jukebox mechanic had to be partially disabled as spigot was corrupting the jukebox tile entity when it’s told to stop playing, and can no longer be checked as for whether it’s currently playing or not

**Comment by me4502** [comment] 2020-05-15 11:58
Actually I misread the original issue made as something else.

I cannot reproduce this issue though? It behaves fine for me if I start it with a button directly on the jukebox?

**Comment by LordRazen** [comment] 2020-05-15 12:26
I tested it again on a empty server, just with craftbook-3.10.2-SNAPSHOT-dist-4573 and Spigot: It IS indeed hard to hear - the disc is started a second time like one or two seconds after the initial start...

C418-13 is a good example: If you insert the CD, there's one "dong" in the beginning, if you press the button, there're two

**Comment by me4502** [comment] 2020-05-15 12:28
Ah, I see what you mean. However, it happens for me whether the button is on the block or not, and is somewhat intentional behaviour atm.

As Spigot broke the ability to turn off the jukebox, making the redstone signal go either high or low both cause it to start the music disc. Therefore, it will start when the button is first pressed, and then again when it unpresses itself after 1 second.

**Comment by LordRazen** [comment] 2020-05-15 12:45
So... basically... wont fix?

**Comment by me4502** [comment] 2020-05-15 12:51
Well, in this case, it's not really a bug, but a partial workaround for a Spigot bug. It does seem odd that it's not happening for you when done through a block

**Comment by me4502** [comment] 2020-10-08 12:59
This is resolved in CraftBook5 using new API I added to Spigot

**Closed by me4502** 2020-10-08 12:59 UTC
Labels: status:platform-issue, type:bug
