### ISSUE TITLE
Gate Dupe While Clicking on the Sign

### ISSUE THREAD

**Issue by 66Beastmaster** [EngineHub/CraftBook#1254] opened 2021-03-24 07:15 UTC
Gate Sign Counts up while Clicking on his Sign
If more fences form same type (dark_oak_fence) are two blocks away in a different direction
I think it needs a timeout.

**Comment by me4502** [comment] 2021-03-24 07:16
Can you provide more information than this?

Last time someone said this, it turns out they just had more fences in the sign on the opposite side of the block. It's also possible you're right clicking it with the item.

Due to the way inventories work in Spigot, this should not be possible, and from this reproduction information it's not reproducable.

**Comment by 66Beastmaster** [comment] 2021-03-24 07:19
I can show it to you on Discord or something.
I spam rightclick with any thing in the Hand or Nothing NO Fance's

**Comment by 66Beastmaster** [comment] 2021-03-24 07:22
![Uploading Unbenannt.png…]()

**Comment by me4502** [comment] 2021-03-24 07:42
Is there a second sign on there? And can you show the surrounding area?

And can you provide your entire latest.log file on pastebin?

**Comment by 66Beastmaster** [comment] 2021-03-24 08:03
Here is the exact Situation for this issue by only one Sign.
![2021-03-24_09 01 33](https://user-images.githubusercontent.com/76445537/112275368-d3f95480-8c7f-11eb-8822-796821d65df1.png)

**Comment by me4502** [comment] 2021-03-24 08:05
Provide logs as requested 

This cannot be reproduced as-is

**Comment by me4502** [comment] 2021-04-05 03:24
Closing until required information is provided

**Closed by me4502** 2021-04-05 03:24 UTC
Labels: status:pending, type:bug
