### ISSUE TITLE
Potion duplication

### ISSUE THREAD

**Issue by Niko302** [EngineHub/CraftBook#1250] opened 2021-03-17 18:03 UTC
**Versions**

CraftBook version: 3.10.3
Bukkit version: 1.16.5 (paper)

**Describe the bug**
You can use pipes to duplicate potions

**To Reproduce**
https://cdn.discordapp.com/attachments/820244381805969430/821506332653912094/Minecraft-1164-Multiplayer-3rd-p.mp4

**Expected behavior**
1 potion

**Screenshots**
Video up top

**Comment by me4502** [comment] 2021-03-18 08:20
Your video doesn't really explain how it's happening. Can you please reproduce it with the smallest possible setup required to reproduce the issue?

I cannot reproduce this

**Comment by Niko302** [comment] 2021-03-19 10:54
> 
> 
> Your video doesn't really explain how it's happening. Can you please reproduce it with the smallest possible setup required to reproduce the issue?
> 
> I cannot reproduce this

https://cdn.discordapp.com/attachments/671448152028741662/822422513505140766/PotionDupe.mp4

**Comment by Marvinha04** [comment] 2021-03-19 10:55
Basically you can fill a brewingstand with pipes, but the bottles don't get taken out of the container. That way it's duping th bottles. I made another video with the most simple setup I could think of. Just a chest, with a Redstone lamp as indicator if the bottle is still in it. And a pipe from the chests to the brewingstand with a lever to trigger.

I hope this helps :)

https://cdn.discordapp.com/attachments/671448152028741662/822422513505140766/PotionDupe.mp4

**Comment by me4502** [comment] 2021-03-19 11:44
I believe I found an issue in some recent contributed code that could cause this, which is now fixed

**Closed by me4502** 2021-03-19 11:44 UTC
Labels: status:pending, type:bug
