### ISSUE TITLE
Fix MC 23w12a edit issue

### ISSUE THREAD

**Issue by Dragsio** [EngineHub/CraftBook#1328] opened 2024-03-30 11:03 UTC
### The Problem

From version MC 23w12a, there is a possibility to edit the labels by right-clicking the mouse. In your plugin, this causes the sign functionality to break when you try to use a sign, such as `[Lift]`.

### A Solution

For example, in another unnamed plugin, they have swapped buttons (left button) for using functional labels, so no editing will happen. Personally, I would like it if the right button remained, but this problem would be solved in another way.

![2024-03-30_12 03 24](https://github.com/EngineHub/CraftBook/assets/48870248/aa694dbb-2fa1-4c3f-a2c0-a96076ea5dd9)

**Comment by me4502** [comment] 2024-03-30 11:05
This is a duplicate of https://github.com/EngineHub/CraftBook/issues/1325. This is also not an issue with CraftBook, but a bug in Paper itself. CraftBook cancels the event.

**Closed by me4502** 2024-03-30 11:05 UTC
Labels: type:feature-request, status:pending
