### ISSUE TITLE
Craftbook + MyPet plugin error

### ISSUE THREAD

**Issue by andris155** [EngineHub/CraftBook#1191] opened 2020-04-22 19:41 UTC
```
[16:45:00] [Server thread/ERROR]: Could not pass event SignClickEvent to CraftBook v3.10.2-SNAPSHOT;4569-b53bc8b
java.lang.ClassCastException: class de.Keyle.MyPet.compat.v1_15_R1.entity.CraftMyPet cannot be cast to class org.bukkit.entity.Vehicle (de.Keyle.MyPet.compat.v1_15_R1.entity.CraftMyPet is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @5b0a1c1f; org.bukkit.entity.Vehicle is in unnamed module of loader 'app')
	at com.sk89q.craftbook.util.LocationUtil.ejectAndTeleportPlayerVehicle(LocationUtil.java:332) ~[?:?]
	at com.sk89q.craftbook.mechanics.Elevator.teleportPlayer(Elevator.java:466) ~[?:?]
	at com.sk89q.craftbook.mechanics.Elevator.makeItSo(Elevator.java:363) ~[?:?]
	at com.sk89q.craftbook.mechanics.Elevator.onCommonClick(Elevator.java:279) ~[?:?]
	at com.sk89q.craftbook.mechanics.Elevator.onRightClick(Elevator.java:230) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor773.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-205]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-205]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-205]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-205]
	at com.sk89q.craftbook.bukkit.MechanicListenerAdapter.onPlayerInteract(MechanicListenerAdapter.java:102) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-205]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-205]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-205]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-205]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:463) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:450) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1378) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1077) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1070) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1144) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-205]
	at java.lang.Thread.run(Unknown Source) [?:?]
```
CraftBook version 3.10.2-SNAPSHOT;4569-b53bc8b
WorldEdit version 7.1.0-SNAPSHOT;4822-a27ade5
[MyPet] MyPet-3.10-SNAPSHOT-b#29

**Comment by me4502** [comment] 2020-04-23 01:11
This was probably caused by https://github.com/EngineHub/CraftBook/pull/220

Apparently when Spigot tells you that the player is inside a vehicle, it doesn't mean it's a vehicle.

I'll look into this tonight.

**Comment by me4502** [comment] 2020-04-23 09:04
Fixed in latest dev build.

**Closed by me4502** 2020-04-23 09:04 UTC

**Comment by andris155** [comment] 2020-04-23 11:38
Thanks!
