### ISSUE TITLE
MinecartMoreRails : Vertical rails could not work at all 

### ISSUE THREAD

**Issue by kyiakiy** [EngineHub/CraftBook#1189] opened 2020-04-17 09:49 UTC
Minecart just ended its journey when it hit the ladder and produce this error in console .

17.04 17:13:17 [Server] ERROR Could not pass event VehicleMoveEvent to CraftBook v3.10.1;d29bd15
17.04 17:13:17 [Server] INFO java.lang.NullPointerException: null
17.04 17:13:17 [Server] INFO at com.sk89q.craftbook.mechanics.minecart.MoreRails.onVehicleMove(MoreRails.java:48) ~[?:?]
17.04 17:13:17 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor27.execute(Unknown Source) ~[?:?]
17.04 17:13:17 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-"0ed6da7"]
17.04 17:13:17 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-"0ed6da7"]
17.04 17:13:17 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-"0ed6da7"]
17.04 17:13:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-"0ed6da7"]
17.04 17:13:17 [Server] INFO at net.minecraft.server.v1_15_R1.EntityMinecartAbstract.tick(EntityMinecartAbstract.java:295) ~[patched_1.15.2.jar:git-Paper-"0ed6da7"]
17.04 17:13:17 [Server] INFO at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:776) ~[patched_1.15.2.jar:git-Paper-"0ed6da7"]
17.04 17:13:17 [Server] INFO at net.minecraft.server.v1_15_R1.World.a(World.java:862) ~[patched_1.15.2.jar:git-Paper-"0ed6da7"]
17.04 17:13:17 [Server] INFO at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:508) ~[patched_1.15.2.jar:git-Paper-"0ed6da7"]
17.04 17:13:17 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1260) ~[patched_1.15.2.jar:git-Paper-"0ed6da7"]
17.04 17:13:17 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-"0ed6da7"]
17.04 17:13:17 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1127) ~[patched_1.15.2.jar:git-Paper-"0ed6da7"]
17.04 17:13:17 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:935) ~[patched_1.15.2.jar:git-Paper-"0ed6da7"]
17.04 17:13:17 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by me4502** [comment] 2020-05-12 05:47
Duplicate of this issue, https://github.com/EngineHub/CraftBook/issues/1197

**Closed by me4502** 2020-05-12 05:47 UTC
